apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: enterprise-project-template
  namespace: openshift-config
  annotations:
    description: "Full enterprise project template with quotas, limits, security, network, HPA, and RBAC"
parameters:
  - name: PROJECT_NAME
    required: true
  - name: PROJECT_DISPLAY_NAME
    required: false

objects:
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    name: ${PROJECT_NAME}
    annotations:
      openshift.io/display-name: ${PROJECT_DISPLAY_NAME}
      security.openshift.io/compliance: "true"
    labels:
      environment: dev
      owner: platform-team
      cost-center: engineering
      managed-by: openshift
      security-level: standard
  spec: {}

- apiVersion: v1
  kind: LimitRange
  metadata:
    name: default-limits
  spec:
    limits:
    - type: Container
      min:
        cpu: 50m
        memory: 128Mi
      max:
        cpu: 4
        memory: 8Gi
      defaultRequest:
        cpu: 250m
        memory: 256Mi
      default:
        cpu: 500m
        memory: 512Mi
      maxLimitRequestRatio:
        cpu: 2
        memory: 2

- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: default-quota
  spec:
    hard:
      pods: "40"
      requests.cpu: "8"
      requests.memory: "16Gi"
      limits.cpu: "16"
      limits.memory: "32Gi"
      persistentvolumeclaims: "10"
      requests.storage: "200Gi"
      services.loadbalancers: "2"
      configmaps: "50"
      secrets: "50"

- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: deny-all
  spec:
    podSelector: {}
    policyTypes:
      - Ingress
      - Egress

- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: allow-same-namespace
  spec:
    podSelector: {}
    ingress:
      - from:
          - podSelector: {}
    policyTypes:
      - Ingress

- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: allow-logging
  spec:
    podSelector: {}
    egress:
      - to:
          - namespaceSelector:
              matchLabels:
                openshift.io/run-level: "1"
    policyTypes:
      - Egress

- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: allow-monitoring
  spec:
    podSelector: {}
    egress:
      - to:
          - namespaceSelector:
              matchLabels:
                openshift.io/cluster-monitoring: "true"
    policyTypes:
      - Egress

- apiVersion: v1
  kind: Secret
  metadata:
    name: default-pull-secret
  type: kubernetes.io/dockerconfigjson
  data:
    .dockerconfigjson: ""
  stringData:
    .dockerconfigjson: "{}"

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: default
  imagePullSecrets:
    - name: default-pull-secret

- apiVersion: autoscaling/v2
  kind: HorizontalPodAutoscaler
  metadata:
    name: example-hpa
    annotations:
      template.openshift.io/expose: "true"
  spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: example
    minReplicas: 1
    maxReplicas: 5
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 80

- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: developers-edit
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
  subjects:
    - kind: Group
      name: developers

- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: admins-admin
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: admin
  subjects:
    - kind: Group
      name: admins
